services:
  db:
    container_name: database_container
    image: postgres:17
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 2s
      retries: 10

  migrate:
    image: migrate/migrate
    depends_on:
      db:
       condition: service_healthy
    volumes:
     - ./migrations:/migrations
    env_file:
     - .env
    entrypoint:
      - sh
      - -c
      - |
       migrate -path /migrations \
       -database "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable" \
        up

  backend:
    build: .
    container_name: backend_test
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  db-data: